# Generated by Django 4.2.1 on 2023-05-17 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carNumber', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='Заводской номер машины')),
                ('engineNumber', models.CharField(max_length=64, verbose_name='Заводской номер двигателя')),
                ('transmissionNumber', models.CharField(max_length=64, verbose_name='Заводской номер трансмиссии')),
                ('driveAxleNumber', models.CharField(max_length=64, verbose_name='Заводской номер ведущего моста')),
                ('steerableAxleNumber', models.CharField(max_length=64, verbose_name='Заводской номер управляемого моста')),
                ('supplyContract', models.CharField(max_length=64, verbose_name='Договор поставки №, дата')),
                ('shippingDate', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=128, verbose_name='Грузополучатель (конечный потребитель)')),
                ('deliveryAddress', models.CharField(max_length=128, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.CharField(max_length=128, verbose_name='Комплектация (доп. опции)')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clients', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DriveAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='serviceCompanies', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SteerableAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failureDate', models.DateField(verbose_name='Дата отказа')),
                ('operatingTime', models.IntegerField(verbose_name='Наработка, м/час')),
                ('description', models.TextField(verbose_name='Описание отказа')),
                ('spares', models.CharField(max_length=255, verbose_name='Используемые запасные части')),
                ('recoveryDate', models.DateField(verbose_name='Дата восстановления')),
                ('downtime', models.IntegerField(verbose_name='Время простоя техники')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='service_app.car', verbose_name='Машина')),
                ('failure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='service_app.failure', verbose_name='Узел отказа')),
                ('recovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='service_app.recovery', verbose_name='Способ восстановления')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='service_app.servicecompany', verbose_name='Сервисная компания')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operatingTime', models.IntegerField(verbose_name='Наработка, м/час')),
                ('order', models.CharField(max_length=64, verbose_name='Номер заказ-наряда')),
                ('orderDate', models.DateField(verbose_name='Дата заказ-наряда')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='service_app.car', verbose_name='Машина')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='service_app.servicecompany', verbose_name='Сервисная компания')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='service_app.maintenancetype', verbose_name='Вид ТО')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='service_app.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='car',
            name='driveAxleModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='service_app.driveaxlemodel', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='engineModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='service_app.enginemodel', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='car',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='service_app.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='car',
            name='steerableAxleModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='service_app.steerableaxlemodel', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='techniqueModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='service_app.techniquemodel', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmissionModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='service_app.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
    ]
