# Generated by Django 4.2.1 on 2023-05-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_alter_maintenance_servicecompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniquemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
